[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "haliax"
version = "1.3"
description = "Named Tensors for Legible Deep Learning in JAX"
authors = ["David Hall <dlwh@stanford.edu>"]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
]

[project.urls]
"Homepage" = "https://github.com/stanford-crfm/haliax"
"Bug Tracker" = "https://github.com/stanford-crfm/haliax/issues/"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
equinox = "^0.10.6"
jaxtyping = "^0.2.20"
#safetensors = {extras = ["numpy"], version = "^0.1"}
jmp = "^0.0.4"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
mypy = "^0.910"
mkdocs = "^1.4.3"
mkdocs-material = "^7.3.3"
mkdocstrings = "^0.22.0"
mkdocs-literate-nav = "^0.6.0"
mkdocs-macros-plugin = "^0.7.0"
mkdocstrings-python = "^1.1.2"
mkdocs-include-markdown-plugin = "*"
pymdown-extensions = "^9.0"
pygments = "^2.10.0"
black = {version = "^22.3.0", allow-prereleases = true}
isort = "^5.9.3"

[tool.black]
line-length = 119
target-version = ["py310"]
preview = true

[tool.isort]
profile = "black"
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 119
src_paths = ["src", "tests"]
